language: python
python:
- '2.7'
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: jsosH1EGPW2sKckXN/nVCGcUCDmAYfa1yVtepvr44KMI3J5KFunu3D9gMWFUJZ17uJakCSBwPCyQfFNjxX2x/Ydh+7uJJnQzX6ttGw4jQvp4KQKtVFaRz53opHZqxYixyVtiE0plxyvbH6PbKq4kOxOZ02qXPByecL+fnBW2nsGSrJFDyGbspMxwXT+qBsBKwbdLQo5sH021VhRZ+3YxrI1RN8P5c2XKwyypVPBbX4pd+765J9o0aCLPL5HmRAu2XwH36MvMSF7W3orOSAP9vPhS9xoBgw/5RFv7R4NZJHfZAej6ifZpsYiu0/q5TCvjT1cuHoaRKKzSQKPZxGMHyPAB22HxPNkzpA749F/QXeLrT65rk6dZ5eVWsElBljqnz3etIeKPmsDa32CHE6Tec5qF4UkaM59kSktYyi22tA9LP/GO+4H61prohWQLmfIqNL64FICKjCBidhlQwwM6vFNzJuPLDz7h1dtIV1Z3lbBX2TvISb4Dsp99iKuCrB2y7oL8FwPbMWHTXnFAeDtv2ihvjCDbEm9nTEqHQnl04w8MyeUVecGz+ZRqUrOOiXPfH16z5+1NpQKez/5f1u5twHaoelEIpDbGw1obo7BndVPOjgXsxa6hKgryR6x9Ph9Om/54rmDsEYYfWl07lcf88+h4TQxqVo0kq30Aq3i2tiI=
  - secure: gymle8Stqtk6aksIdhJaUT5CtHpcihZyq3ICEnVZYRhPCc9QOL380aJKjgqbOyibZY5zT78VnNcUkkztAzK1TwRrqRekpdUuPZZrPkQ8dpBMrjRfEBB2ZVgZCf+FaH0Y3qZgbRHibsVU0Aq4Et9xnj9JXwwj5XscW/g18vocTrYes5Lfu2uG9BwgxUiSkfe57JMEFenMghOjePPNs1CfGz+MLVW8GQS6e4KoGHrClLMJu9oRHv1CTBJJcVjeUbuYYakBBpxtVhYb/j0DlaqVs/nISbgcvcf8yfU3xMPj+T1i6xk1+trBGmlSCHYGc2k5SI6J5hPOXu03XDxYHGIvqzG8mLGdIPPtvDAmaP4bV26efhts9ipUOGSw2SfxIUDp7IxvOzs6I0TogL96pwos/J+aW4s++3CZsaN65agaODarXhUKSea4bi5Kq418C01IUr5eEWw1ThzYnBlwH2wWacMxMOV9TUiHP2hSnNiSMnodWxtF4ZGSajagl+51U96qPJHjzX//PLEMJ3iDDYyEQHxcCsytaMmlBQLa84qVxomlfHaQCgUprubRH75btuRCvFke6H4NPQJb5BtRY+06j0GLYEkVg4OQXDZUgPFKYiFLqPjzDgGKaviOAU5YL5DgopcXS1tD6uFwciA+dzPwwTPM3DlezcaxSEq/rFU4vFs=
  - secure: PQ418l2Tzf+uLrGMtCBlLmKO5uJVo2tCwQzfOCzKmKpeTiNhuETHRun172F2NYaKu1eN4I/MFWKATYiXGH7ppdMqJFiF1YOn6p4atmm6sLjdKlTFFXOfXS0cJrYfIz7t7uN/sdRSiaJwVegzwzcxpqOGE0LNSDgqplSZncJc5L4ykspKicnLmQ7RntcqzrjnzBaW0grr/1Re4G8dQjwc0XYjdNsfw8wIEA3hRTUBGRdUE9stcxdRNdqpAgeDIM2B0Qedrl1ErQ9BJ9fw0cBm5d82yO2oBkAgbPKiN4Zs6tdYx3u6PJAgStI+7M5yNhr3D+OSXicsHZubLq1CgSoQuKRCP0eumvNsKtD3xfPGhMADMX8O1VjFhZXFVNx/jhhBVoLbMeuyTSoa20E+8spYu2oWIGyjfn7V7nefqQNT9BhWo1oUdzlzQSzpwHX7NihbMU2ByB3nVsaN5GrUTJFeetpifD0wZnuEAVLG0Wwooewt57aNmhHQArHsg5OeMpn+dTS9BILoSzzRYHEi0GIa9j+dHOs2a1n20MJBEcuBPW1osSZ4HpzghN9Lyxo+5nW2MbAGHUUESsFVAXlvk8EnPasN8/3LBfpUTbH+JqML7dN2tlM3dhdPCz80sHl8ul2PUpEyOGNjPROhCdU+E4480RPHkLafniuWo6bXhn7N8Ec=
before_install:
- openssl aes-256-cbc -K $encrypted_c5958a5e2039_key -iv $encrypted_c5958a5e2039_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip install ansible==2.5.0 molecule==2.12.1 ansible-lint==3.4.19 apache-libcloud testinfra
  PyCrypto
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule --debug destroy
notifications:
  slack:
    secure: xRlUdUPxCGhw7iSOmnRqTyuxbvvu9Fq7jBScHGN7+zHv8h/k+5aaNbCoqS91QQsZZHZ9vCGTdN9B8XYW9lQ51vkOZewAFJyGgo7KbJSz0lD/cREC5zBPHfox0/xqEY/ZwnRFZ839WVD2M7VGPe0ms1EtIwXwJje6OSfWox23l3nrj063RxztHy5oPi6utD6WhhQE80N0M3+lqY9dIAZn6zO0gq+BNrd1xFdSRxnmvbbSMTZAMYSvrJeu5ti6Ic+HcIFv+aW/7anO9Iej+dIPGZ/+Tfn2o7Mli7tb5ZJs4ZBsaYNX4anrJCAazkwkeJeVhQ6qjihjt+aiaj6eSLXrid5O3Xox2hfAAZpSWhNNzSRiRD9QzLkDuIwlFL+o/Bz2pkuKdNBtjGgngYlZ8ufZ1DIaFNaLtX87jFJLD19FfBuVZRztfl1aTVKyL2Xb6xJyIPVQy+rGLMabhxz39O6wtFrmsaHZ1VryKt86ViE9hSJUC7myeQ665latgfbbCY9QtIKyHhNr1gUbrim/QbrY5+JEAi1cJHmLQjuvnHU13CYvhgFe0+wCoMqGlRy7WDVcYoRzV2Wm6yPLQlF5fu2FEmO7n/N5wcuV7m+5SGCXV9uowjH+SRi0x9Xpu5TaUHg0673vqUTKc0jQqCoO4UbrWqA+5Q1gE38hJ3J7Frmay5A=
