language: python
python:
- '2.7'
env:
  global:
  - GCE_CREDENTIALS_FILE="${TRAVIS_BUILD_DIR}/credentials.json
  - secure: HIfytxHyzotyjH1mxGFciQUt5ydm0DbquYIVzIaZQ9Dr+eK+G1DkCXjx2QGtAs8bX6OPag/2tlmBIufCq1zV7J/HotEbeU5baDrcyM7Rh2m7sIxGADwxp5ZEjxIWYG1oyLZcxkH5bmJP9qjmF18hzATYde2myd08a2HHswax1r1nO+TEEBmXETF6hlJjJDLNrGH6WdrfKvJkfOaY2lhLTD2MWKNepSZ6zscOioAOW81Q2l1nJa4Tn4HyGtkHTRtML4+b/wp2lOLVjAI3NuFaI4UOu8eF4q7E0Mp2INDFEQVK2Rel1rsmBO9YMtEVZ4qU+j3kUyiK0zpTcikzqslWH29hFrv+UyfwsNE1/aVoH9OsjS8Z1/a2JVBDy0dmgVknyLGcYwoG7oZoOkJdv+I0Um9QpLOEaz8FuQXS/v9qIFSttn5Vzw3vK10OST6iE2Ih/BuRRZJb8mH7V27R1rgmFVLQ8SOIE2sx8TabpAIOlnsfi5gk89aSxHj0l8YUVWFssLjid1nILHNfWk2bV9QyKudqaQhVE0EyMo8gsgriOZ9e0l+9ryqyCtUP7tu/+dK0txBBxJysFYJUY0af+aoGAoiT2Pb4BYZkItgV0sugN3HzzAIGad3ggriRoyVYakJixWsQ54GbPBfB3zkuMct7mh2KRfBjuY9q95GLhutda5U=
  - secure: f7OAO04ZkcigbILHFWftW/I8bBMSI6cS4bk430mojeQI36LYxPiVWdae0lYV51lDkA0wfYAKFglX0By55qjP1G0VT1GCfJKI79u27qdb3dPLT4gmt1EPFBEA3M2Dkxbw+stgGUqwFsn/QAvI05AWXy+qcwyF0+at3b4uKY/JZuiCEqV8e3oCXb/6664y5rdFJW3C4NgkW7I7MoiLqKVkFZ6cpBok9JEul9BF1UNC5CqjzmjX9FZUmINceFligSMxluiasW+U4VrB2xFtoeY8Cns5kvtGg9mjJZg8N+HTbWTCknIOGwXoIcIeJHbOoHeakVP3VMp3ZTq2sqsJbBD4Ynx4diAw2IvBdXASCZnydcfd09/UvRVwTUC7tkprc0Me/i70QDm8RngmVNuNHOgcLS8ABMdure8MfblfczF8JWpnO+/Py7YiOXYHbmYAYNzQTygMbVS5pT7ZDbpmLRttg1RrF/4FEhqjQ42agYOdZNn+xNKX/FWrBFWYy9/DoV1zZr4qzV+30IkPD0hP3gp4dQKgyc169xYtGl16J0H1Unl8ozMcrAc47H7/jAV2uRJ8O8fHoSV6rx5T3g1UiuJ+YRxl41Wkf984tj0N2xCM9OYPRf9SNz+M8P5jqYERKA+LxTGYiNKHUFXZpVaMw6KvD30xSNiZXnWiwN2q+TbEX0k=
before_install:
- openssl aes-256-cbc -K $encrypted_c5958a5e2039_key -iv $encrypted_c5958a5e2039_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip install ansible==2.5.0 molecule==2.6 apache-libcloud
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule --debug destroy
notifications:
  slack:
    secure: xRlUdUPxCGhw7iSOmnRqTyuxbvvu9Fq7jBScHGN7+zHv8h/k+5aaNbCoqS91QQsZZHZ9vCGTdN9B8XYW9lQ51vkOZewAFJyGgo7KbJSz0lD/cREC5zBPHfox0/xqEY/ZwnRFZ839WVD2M7VGPe0ms1EtIwXwJje6OSfWox23l3nrj063RxztHy5oPi6utD6WhhQE80N0M3+lqY9dIAZn6zO0gq+BNrd1xFdSRxnmvbbSMTZAMYSvrJeu5ti6Ic+HcIFv+aW/7anO9Iej+dIPGZ/+Tfn2o7Mli7tb5ZJs4ZBsaYNX4anrJCAazkwkeJeVhQ6qjihjt+aiaj6eSLXrid5O3Xox2hfAAZpSWhNNzSRiRD9QzLkDuIwlFL+o/Bz2pkuKdNBtjGgngYlZ8ufZ1DIaFNaLtX87jFJLD19FfBuVZRztfl1aTVKyL2Xb6xJyIPVQy+rGLMabhxz39O6wtFrmsaHZ1VryKt86ViE9hSJUC7myeQ665latgfbbCY9QtIKyHhNr1gUbrim/QbrY5+JEAi1cJHmLQjuvnHU13CYvhgFe0+wCoMqGlRy7WDVcYoRzV2Wm6yPLQlF5fu2FEmO7n/N5wcuV7m+5SGCXV9uowjH+SRi0x9Xpu5TaUHg0673vqUTKc0jQqCoO4UbrWqA+5Q1gE38hJ3J7Frmay5A=
