language: python
python:
- '2.7'
matrix:
- GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
env:
  global:
  - secure: EeXY3c06IRMvmEpobAgBiwfiBusMX+n6kFXDYX9rzcidWP9SqsS6vbvj627TcCa3jUQ119/D8Vj9r9a1Kl4TD7mBorQd8susDPsX32v6XeCKCtt7fWM2duOU9Qp5oODCB8LPe5hwtp6lxe3o9oNkRQp9LIrW/S146I0ZWywiQ3pVhwPdUHVeGs0tDRkrVC1NvAICDDMxni8tmJ70no8MQTMecokj8rw6gXtkYa4qeYgeVYCcp3HLtq/O9zi5cnvyiY8a+i492490zNYvVALDzDIK80QINFDgAgX0tFSIG73xCIm/P44KB6f9Gnk0H9uLwfi9Bh01M7jgA1mrC4RnP1BlgZ2Sqx8B0w6Y2Ig9lrKz3KQAO8q+hI9NwSApp20s13/kfFNVjoa+HBylkFvrBp3r+yYhhelhDV0jjwl0uNAJBGSYiVLvVNCgHMRf2ru1Fv7V94fUi9Jf4xw2sL9FwrpsNrCOL5qeQam2BE92ANsvDqUZ2P3pUbFbDd8lyxsFhH5UM3CuIP6b4R3Wp3STvRhwH8tQuVa5QMG0lpaiMatb5X28iaqkdUkUkUMeBuf+VXQ2gzLJBOibuEWiWVWq2TwHu9QqwULnALJ3wFjij9ld+71P7UJnimDGGTeZxCcnWYT6rhLLaTM8cQxOn5MiXJIj4yRUH+j/2CIsK8tcnk0=
  - secure: gcmVQAMR/G8hdZXhX6kZxikQ6l8TUpu443NNYrLiVV8h+nQUn0+Ntt/ce5xb3yX48BmiI9n/rgBMeEURK7iONxLPyfgjikgXm87MV+Vq9aasf0CA7cVrwjkegaw9pDvMLu9f6JgXQl5lgGFaRlivIZWhr62dRgIKbjeoHXdmFr4dNpMjihUWCTQrLh2crMs/yDx6Ghmlcl6ImJy36Holzty68M/9aRRfJlkdAxarPMH+/NFWEWuYwkBgvcVsJwOko1IAYO466KC+NlyUm6BGj0GovTJeFPplJP8PxIPfk2//P3FNsm5cFnIJDh95qBdw5OULTvTug9+VON+UifkSg4i5NwG3sCpFVw4+Vc6Lu3e+Ig1LsJ8oa6aA8bnGGIy/PzuE4axxD5zFXQSHA5hUCC7Ym+a83VSlXwa9UmcTSWVPBPeN+ErCD6Ati2zID1Yynds56uaLaZ4v/ACIk5ZARcr9qTXANWGV3pOpHr2rQniC9L/O3IbkH9GYBxaKKSm+sOY0ERvwm7g6CG1qJFu41LfhNOOsAg+CPvdu9pfsbSDyjMtz70+cPy5eDSxo4JxuMlpTfbvGelWA7mQsO0XQhfaVZ8eLO1ft4cbBp+JXbNjTpowxlX6I7iZrlZDAv+jKl+BAIAigge2CR+6cru7dN+DWb7NpGykc7vNq5WQLbgw=
  - secure: kAPXo2vr4/FY0kLEZw5d8vfrTMp/KK2JfD2Ke8RjYO2ZyxnbpdcUx4T8p/cLbpBUO0IqUDKzJQpLFqCkmihhnU6+s7tGpfUIF4Jj7Ytj/QqyF3eMVJ7a/h9a0tLur2Y8Uck6PGMwIl//41EuLEL8SxJlIOw4JcisADkcnGopJ4VP7l1FneaGxDS310gIaEIyInTcS3yrcLo6rywUynC5i9p8JTV2RcFhignrQ7gz9e1BQcju9RQdiA7KUfHzwtiQ9uLQ9nlMWr9DukfTwgLRGw1L0U7nVqZox7ptNRVthpfKAsSNpD+jPSo2/fLkF2sBSdWggV7nSRE9HphL7J++GkB3kOM+QVbnUkcjKa2wr5UUcwN47W6Q7irANdafNPBezYImBj7b+4OJqr9FcY+MXm2yiqUQvDbX8IDpW954CTjqrsbP92uRJMXOFSY7yNGV6c4g2PvcKJ4FM0f/ZtLZ/MM/zk38PgI3DiXoM+mXvsJy6zyy7IwAqTsx9ZDRSaKtOV9/hJy0ANCk89qaAnTH8mgYPDKwgtwacHlJOTzRfNLrIn1yfcCJO3Gng8FBs1a8ww8iGwkKFJZUAnlxlQiKuHr26RAVpiS81y+R6xC61GvYPtHrWLm+OlKeDTQCgBz2jgaJSE/F5ybtHAkH86CEB+jTCNvNei2femalKgV7Qq4=
before_install:
- openssl aes-256-cbc -K $encrypted_c5958a5e2039_key -iv $encrypted_c5958a5e2039_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- ls -lha
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip install ansible==2.5.0 molecule==2.6 apache-libcloud
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule --debug destroy
notifications:
  slack:
    secure: xRlUdUPxCGhw7iSOmnRqTyuxbvvu9Fq7jBScHGN7+zHv8h/k+5aaNbCoqS91QQsZZHZ9vCGTdN9B8XYW9lQ51vkOZewAFJyGgo7KbJSz0lD/cREC5zBPHfox0/xqEY/ZwnRFZ839WVD2M7VGPe0ms1EtIwXwJje6OSfWox23l3nrj063RxztHy5oPi6utD6WhhQE80N0M3+lqY9dIAZn6zO0gq+BNrd1xFdSRxnmvbbSMTZAMYSvrJeu5ti6Ic+HcIFv+aW/7anO9Iej+dIPGZ/+Tfn2o7Mli7tb5ZJs4ZBsaYNX4anrJCAazkwkeJeVhQ6qjihjt+aiaj6eSLXrid5O3Xox2hfAAZpSWhNNzSRiRD9QzLkDuIwlFL+o/Bz2pkuKdNBtjGgngYlZ8ufZ1DIaFNaLtX87jFJLD19FfBuVZRztfl1aTVKyL2Xb6xJyIPVQy+rGLMabhxz39O6wtFrmsaHZ1VryKt86ViE9hSJUC7myeQ665latgfbbCY9QtIKyHhNr1gUbrim/QbrY5+JEAi1cJHmLQjuvnHU13CYvhgFe0+wCoMqGlRy7WDVcYoRzV2Wm6yPLQlF5fu2FEmO7n/N5wcuV7m+5SGCXV9uowjH+SRi0x9Xpu5TaUHg0673vqUTKc0jQqCoO4UbrWqA+5Q1gE38hJ3J7Frmay5A=
