language: python
python:
- '2.7'
matrix:
- GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
env:
  global:
  - secure: rKutFzO8adgW7MNx+DXH70t1MOZ7TlfpZoVl5hHDBxVfjCNA6lGdGhDsglTlf1RA9pZyOjtLB/bKooqui4ru1b0/nkoxPGwfqpxolyRoUiOIyaVxjsKwDYsp5DCf76nbSJ4vZUzvm+/P38r5pPGIvyZrQCaq64l7N6/lsMNoIjZiifhSgzFJ3PgKXvakbHalHgpYoBROzE+ffuJzMPbumAX9HYq9yWjo3tCv4Fs17FY5mqYHTmXqCN4+D14cHkyhS1BmsAyRa5txHfn8VHMQ2ooSKaiAwoLphl1rp3rNzxyQKdNCEA2hdL61vDy/KKuIfNSs3TFXS8CRWXKvUN9Fs/QkXcqhpCotSO5gzUPxlUSO/4DsAGrb2oMKzoIABnIRC0iBZMr+O+woT0so+404e5WHcz++8/wGdpzOtyfXtF6hCSQ8gy1z5HvDJhEBAgDTpPGQ6C+xRu8s7cw5SvaKcdaINYrFT4FV0/Nb8g1W5j4nIMVGpxtMI5LhSw9Hd4C/G4V/jDWEasV4l5egxgfg9CqIw83qgLOthK/XccJhwlQEjcIGP1My+p3jEmxVVnY75ywcwYDUK6zNe0Wdnf0DPlhYioa+VCpu8TNE1elHN0MCZoU+HDACr3097zzZI+A+J0eaksNcRV7A3o1ypnoT1b17r37To4xXTr8hYmeD9Xk=
  - secure: VMdtjg2YXsRA1E2Hvu64S3D0dr1VzifXemvnFQMk5qEWFy2+Iv66CFVlaK1AAwzln/QMe6PHHFhSH6D7ICfsVzoUZNBRv1GBRcJJ0cgosp9lNbVyzdVDOOAlQ63vixq+OfS2hmFWJsok6kWcUQdXm4nQpbJz2ciRlI+U6jgDIFw9aqXp7LtjNwlbjMuZx6TpjB55U4BTS95rnhhvYPJEvH+WhwFOKCH1BeknL2BTgtf2E/jQc0JCTtEFcIBEyexPdx12r2g3vloHxX5SFZ7RbMhnLEOhNZb/mz3cNPnoPhZ1saOSjAZO5Ir1wjo+J5VaVkJCPYz4sWXGtJ48nDQUcB4DqIdv2fz85piltquiNhJvNWvdyTyArYc6AZlNPaiG8UHREOIh/BGCPfKvoZ4o4SJgkSSPiUhJmQHu1FXG1jCYgQywpdM2HOr9l0bC7Ig56IJz3PHj2TIjqU9T9w0Y91416BXuYwRc2yMFM1FZs/hq/OAR+bnPC92LvUUGqiZc3GM4X8k3ztKmO18P8F1a9+zSt6n/LsQitGB4BSI0iLxaQ8VwCMFdHaneOQx2yk48DxGdVcxfH1ykSKnt+0FeAVnL0QZAuVS9xo+AAfkY6B3csv27L0NbkpWY0krEOd6HU9/qhSuvPgHNuSdBVq97o83vO/cX+gg73RJsPBmyhdI=
  - secure: rB6L6wCcmIWPQ/FNUGGNlPBa8YAszPrtINmv+C481EGn8305bwS1enZ4T54rfSIjQMTWj3sMzAso5NCT6EUlbofXxaQrfMUJs091sGISVzHAZl4tWYN9X5eVGpgwqaSnZSDKNBZWkZqzqXyeiVKeLsS5vFaGILHCXxraCeaw1tpBzZ8BuoC4E+SDF8S/U860GCLk7g8A7n7RBz5pdyCWVDQq77jUBjpDN9GL2PpGp+Pzpn1rqWeC0tVdbLD+GeUsW5Q/HhnZNlHTGpi14lMIblZ7wo8Sap9YrmdkichoHZPVIjiGbukmfhVaVPDjFGSl89Ngv12parfC7N4Nl6iul1IRLMwlMYdKLzmyfBTtOdaz37nMb4RTp/2tvWBif4McElGww28h+RZicGndabX4jLCPv2c0oOGO2zS6bN2McyJNOZc219VcS8x08E8ERfQP4LF0rfof6dY8cm15ldkI3JwO4+1sK0kW4Glz+e2iBMDWoZUj3liOMWkVhOshF84xPZWukq5a2lbkoYO25KrfaFFTkEEXW6TM3YDfvzY8SjpHz+lNaRdcHb6ZaGOJI4+dhgz8S9dSD7GLN79LZ2t+hyJPKpMh5qVnirrAASHEPhhjISP8QnXfeg2L8CqQaoLRB4ckP04imZuFg53Gltr9XRcARVjt4EdL3f+wh89/WL4=
before_install:
- openssl aes-256-cbc -K $encrypted_c5958a5e2039_key -iv $encrypted_c5958a5e2039_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip install ansible==2.5.0 molecule==2.6 apache-libcloud
script:
- ls -lha
- echo $GCE_CREDENTIALS_FILE
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule --debug destroy
notifications:
  slack:
    secure: xRlUdUPxCGhw7iSOmnRqTyuxbvvu9Fq7jBScHGN7+zHv8h/k+5aaNbCoqS91QQsZZHZ9vCGTdN9B8XYW9lQ51vkOZewAFJyGgo7KbJSz0lD/cREC5zBPHfox0/xqEY/ZwnRFZ839WVD2M7VGPe0ms1EtIwXwJje6OSfWox23l3nrj063RxztHy5oPi6utD6WhhQE80N0M3+lqY9dIAZn6zO0gq+BNrd1xFdSRxnmvbbSMTZAMYSvrJeu5ti6Ic+HcIFv+aW/7anO9Iej+dIPGZ/+Tfn2o7Mli7tb5ZJs4ZBsaYNX4anrJCAazkwkeJeVhQ6qjihjt+aiaj6eSLXrid5O3Xox2hfAAZpSWhNNzSRiRD9QzLkDuIwlFL+o/Bz2pkuKdNBtjGgngYlZ8ufZ1DIaFNaLtX87jFJLD19FfBuVZRztfl1aTVKyL2Xb6xJyIPVQy+rGLMabhxz39O6wtFrmsaHZ1VryKt86ViE9hSJUC7myeQ665latgfbbCY9QtIKyHhNr1gUbrim/QbrY5+JEAi1cJHmLQjuvnHU13CYvhgFe0+wCoMqGlRy7WDVcYoRzV2Wm6yPLQlF5fu2FEmO7n/N5wcuV7m+5SGCXV9uowjH+SRi0x9Xpu5TaUHg0673vqUTKc0jQqCoO4UbrWqA+5Q1gE38hJ3J7Frmay5A=
